export const genres = [
	"A Cappella",
	"Abstract",
	"Abstract Beats",
	"Abstract Hip Hop",
	"Abstract Idm",
	"Abstractro",
	"Accordion",
	"Acid House",
	"Acid Jazz",
	"Acid Techno",
	"Acousmatic",
	"Acoustic Blues",
	"Acoustic Pop",
	"Adult Standards",
	"African Percussion",
	"African Rock",
	"Afrikaans",
	"Afrobeat",
	"Afrobeats",
	"Aggrotech",
	"Albanian Pop",
	"Album Rock",
	"Albuquerque Indie",
	"Alternative Americana",
	"Alternative Country",
	"Alternative Dance",
	"Alternative Emo",
	"Alternative Hardcore",
	"Alternative Hip Hop",
	"Alternative Metal",
	"Alternative Metalcore",
	"Alternative New Age",
	"Alternative Pop",
	"Alternative Pop Rock",
	"Alternative R&b",
	"Alternative Rock",
	"Alternative Roots Rock",
	"Ambeat",
	"Ambient",
	"Ambient Dub Techno",
	"Ambient Fusion",
	"Ambient Idm",
	"Ambient Psychill",
	"Ambient Trance",
	"Anarcho-punk",
	"Andean",
	"Anime",
	"Anime Score",
	"Anti-folk",
	"Antiviral Pop",
	"Appalachian Folk",
	"Arab Folk",
	"Arab Pop",
	"Arabesk",
	"Argentine Indie",
	"Argentine Reggae",
	"Argentine Rock",
	"Armenian Folk",
	"Art Rock",
	"Athens Indie",
	"Atmospheric Black Metal",
	"Atmospheric Post Rock",
	"Atmospheric Post-metal",
	"Aussie Pop",
	"Austrian Pop",
	"Australian Indie",
	"Australian Rock",
	"Autotune",
	"Avant-garde Metal",
	"Avant-garde Pop",
	"Avant-garde Rock",
	"Bagpipes",
	"Baltic Folk",
	"Baltimore Indie",
	"Banda",
	"Barbershop",
	"Baroque",
	"Baroque Pop",
	"Baseball",
	"Bass Music",
	"Bass Trap",
	"Bats",
	"Beatdown",
	"Beats",
	"Big Beat",
	"Big Band",
	"Biker Rock",
	"Bossa Nova",
	"Brazilian Folk",
	"Brazilian Pop",
	"Brazilian Rock",
	"British Alternative Rock",
	"British Blues",
	"British Breakbeat",
	"British Dance",
	"British Folk",
	"British Glam Rock",
	"British Hip Hop",
	"British Indie",
	"British Jazz",
	"British Metal",
	"British New Wave",
	"British Pop",
	"British Pop Rock",
	"British Rock",
	"Brostep",
	"Celtic",
	"Celtic Rock",
	"Chamber Pop",
	"Chicago Blues",
	"Chicago House",
	"Chicago Indie",
	"Chicago Jazz",
	"Chicago Rap",
	"Chinese Folk",
	"Chinese Pop",
	"Chinese Rock",
	"Chiptune",
	"Christian Contemporary",
	"Christian Death Metal",
	"Christian Hardcore",
	"Christian Metal",
	"Christian Pop",
	"Christian Punk",
	"Christian Rock",
	"Classic Baroque",
	"Classic Blues",
	"Classic British Rock",
	"Classic Country",
	"Classic Folk",
	"Classic Funk",
	"Classic Hip Hop",
	"Classic Indie",
	"Classic Jazz",
	"Classic Metal",
	"Classic Pop",
	"Classic Punk",
	"Classic R&B",
	"Classic Rock",
	"Classic Soul",
	"Classical",
	"Classical Crossover",
	"Classical Guitar",
	"Classical Percussion",
	"Classical Piano",
	"Classical Symphony",
	"Clowncore",
	"Comedy",
	"Comedy Rock",
	"Composers",
	"Concrete",
	"Confusionism",
	"Contemporary Christian",
	"Contemporary Country",
	"Contemporary Folk",
	"Contemporary Gospel",
	"Contemporary Jazz",
	"Contemporary Metal",
	"Contemporary Pop",
	"Contemporary R&B",
	"Contemporary Rock",
	"Contemporary Soul",
	"Country",
	"Country Blues",
	"Country Folk",
	"Country Pop",
	"Country Rock",
	"Cumbia",
	"Dance",
	"Dance Pop",
	"Dance Rock",
	"Dancehall",
	"Dance-punk",
	"Dark Ambient",
	"Dark Cabaret",
	"Dark Electro",
	"Dark Folk",
	"Dark Jazz",
	"Dark Metal",
	"Darkwave",
	"Death Cab",
	"Deathcore",
	"Death Metal",
	"Djent",
	"Doom Metal",
	"Drone",
	"Drone Ambient",
	"Dub",
	"Dub Electronica",
	"Dub Reggae",
	"Dub Techno",
	"Dubstep",
	"Electroacoustic",
	"Electroclash",
	"Electronic",
	"Electronic Dance Music",
	"Electronicore",
	"Electronica",
	"Electropop",
	"Electronica Indie",
	"Electro Swing",
	"Emo",
	"Emo Pop",
	"Emo Punk",
	"Epic Metal",
	"Experimental",
	"Experimental Jazz",
	"Experimental Pop",
	"Experimental Rock",
	"Folk",
	"Folk Metal",
	"Folk Pop",
	"Folk Rock",
	"Folk Punk",
	"Free Jazz",
	"Funk",
	"Funk Rock",
	"Fusion",
	"Garage Rock",
	"Gospel",
	"Goth",
	"Gothic Metal",
	"Gothic Rock",
	"Grime",
	"Grunge",
	"Hard Dance",
	"Hard Rock",
	"Hardstyle",
	"Hardcore",
	"Hardcore Punk",
	"Heavy Metal",
	"Hi-NRG",
	"Hip Hop",
	"Hip Hop Rap",
	"Horror Punk",
	"House",
	"House Music",
	"Indie",
	"Indie Folk",
	"Indie Pop",
	"Indie Rock",
	"Industrial",
	"Industrial Metal",
	"Industrial Rock",
	"Industrious",
	"Industro Punk",
	"Irish Folk",
	"Italo Disco",
	"J-Pop",
	"Jazz",
	"Jazz Blues",
	"Jazz Fusion",
	"Jazz Funk",
	"Jazz Rock",
	"J-Pop Rock",
	"K-Pop",
	"Krautrock",
	"Latin",
	"Latin Jazz",
	"Latin Pop",
	"Latin Rock",
	"Lo-Fi",
	"Lounge",
	"Lullaby",
	"Math Rock",
	"Melodic Death Metal",
	"Metal",
	"Metalcore",
	"Microhouse",
	"Minimal",
	"Minimal Techno",
	"Modern Classical",
	"Modern Jazz",
	"Modern Metal",
	"Modern Rock",
	"Noise",
	"Noise Rock",
	"Nu Disco",
	"Nu Metal",
	"Nu Soul",
	"Old School Hip Hop",
	"Orchestral",
	"Post-apocalyptic",
	"Post-hardcore",
	"Post-punk",
	"Post-rock",
	"Post-metal",
	"Pop",
	"Pop Folk",
	"Pop Punk",
	"Pop Rap",
	"Pop Rock",
	"Pop Soul",
	"Power Pop",
	"Progressive House",
	"Progressive Metal",
	"Progressive Rock",
	"Psychedelic",
	"Psychedelic Rock",
	"Punk",
	"Punk Rock",
	"Punk Pop",
	"R&B",
	"Rap",
	"Reggae",
	"Reggaeton",
	"Rock",
	"Rockabilly",
	"Romantic",
	"Soul",
	"Soul Jazz",
	"Synth-pop",
	"Techno",
	"Trance",
	"Trap",
	"Tropical House",
	"Vaporwave",
	"Viking Metal",
	"Western",
];
